// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Diagnose(arg1, arg2) {
  return window['go']['main']['App']['Diagnose'](arg1, arg2);
}

export function ListArchives(arg1, arg2) {
  return window['go']['main']['App']['ListArchives'](arg1, arg2);
}

export function ListClassCaches() {
  return window['go']['main']['App']['ListClassCaches']();
}

export function SampleSavingsFromKind() {
  return window['go']['main']['App']['SampleSavingsFromKind']();
}
