// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Diagnose(arg1:string,arg2:number):Promise<main.Diag>;

export function ListArchives(arg1:string,arg2:number):Promise<Array<main.ArchiveSummary>>;

export function ListClassCaches():Promise<Array<main.ClassCacheSummary>>;

export function PodStats():Promise<Array<main.PodStat>>;

export function SampleSavings():Promise<main.SavingsSnapshot>;
